name: stocks_news_new
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.09+77 # android
# version: 1.1.09+66 # ios


environment:
  sdk: ">=3.2.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.5.0
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  validators: ^3.0.0
  collection:
  http: ^1.1.0
  intl: 
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.2.1
  provider: ^6.1.2
  # device_info: ^2.0.3
  # device_info_plus: ^9.1.1
  # connectivity_plus: ^5.0.1
  package_info_plus: ^5.0.1
  syncfusion_flutter_gauges: 
  pinput: ^4.0.0
  flutter_slidable: ^3.0.1
  change_app_package_name: ^1.1.0
  firebase_core: ^2.27.0
  google_sign_in: ^6.1.6
  google_sign_in_ios: ^5.6.5
  # upgrader: ^8.4.0
  firebase_analytics: ^10.8.9
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^16.2.0
  webview_flutter: ^4.8.0
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  flutter_image_compress: ^2.1.0
  flutter_widget_from_html: ^0.14.9
  fl_chart: ^0.68.0
  auto_size_text: ^3.0.0
  path_provider: ^2.1.2
  # qr_code_scanner: ^1.0.1
  flutter_keyboard_visibility: ^6.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  sign_in_with_apple: ^5.0.0
  responsive_builder: ^0.7.0
  svg_flutter: ^0.0.1
  percent_indicator: ^4.2.3
  # uni_links: ^0.5.1
  share_plus: ^7.2.2
  cached_network_image: ^3.3.1
  simple_gradient_text: ^1.3.0
  flutter_isolate: ^2.0.5-pre
  lottie: ^3.1.0
  vibration: ^1.8.4
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  # syncfusion_flutter_charts: ^25.2.3+1
  firebase_in_app_messaging: ^0.7.4+17
  modal_bottom_sheet: ^3.0.0
  app_links: ^6.0.2
  audioplayers: ^5.2.1
  readmore: ^3.0.0
  # socket_io_client: ^2.0.3+1
  web_socket_channel: ^2.4.3
  flutter_html: ^3.0.0-beta.2
  # flutter_offline: ^3.0.1
  connectivity_plus: ^6.0.3
  photo_view: ^0.15.0
  plaid_flutter: ^3.1.8
  sqflite: ^2.3.3+1
  in_app_update: ^4.2.3
  in_app_review: ^2.0.9
  flutter_rating_bar: ^4.0.1
  sms_autofill: ^2.4.0
  firebase_dynamic_links: ^5.4.17
  fluttertoast: ^8.2.5
  firebase_auth: ^4.17.8
  purchases_flutter: ^6.29.4
  purchases_ui_flutter: ^6.29.4
  flutter_animation_progress_bar: ^2.3.1
  dotted_border: ^2.1.0
  multi_charts: 
  google_fonts: 
  charts_flutter:
  # syncfusion_flutter_gauges:
  slide_to_act: ^2.0.2 
  # fl_chart:

  # flutter_keyboard_visibility: ^6.0.0
  # flutter_branch_sdk: ^7.1.0
  country_code_picker: ^3.0.0
  webview_flutter_android: ^3.16.4
  flutter_pdfview: ^1.3.2
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/json/coin.json
    - assets/svg/
    - assets/fonts/
    - assets/fonts/roboto/
    - assets/fonts/georgia/
    - assets/fonts/ptSans/
    - assets/
    - assets/images/
    - assets/audios/
    - assets/audios/alert_watchlist.mp3
    - assets/audios/refresh.wav


    # - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
    - family: Georgia
      fonts:
        - asset: assets/fonts/georgia/Georgia-Regular.ttf
        - asset: assets/fonts/georgia/Georgia-Bold.ttf
          weight: 700
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
          weight: 700

    - family: PTSans
      fonts:
        - asset: assets/fonts/ptSans/PTSans-Regular.ttf
        - asset: assets/fonts/ptSans/PTSans-Bold.ttf
          weight: 700
